# Encoding of the source code. E.g.: UTF-8, MacRoman, Shift_JIS
sonar.sourceEncoding=UTF-8

# Comma-separated list of file path patterns to be excluded from analysis
# Exclude test subdirectories from source scope
# E.g.: /third_party_module1/**,/third_party_module2/**
sonar.exclusions=**/tests/**/*

# Comma-separated list of file path patterns to be excluded from duplication detection
# Exclude test subdirectories from duplication scope
# E.g.: /third_party_module1/**,/third_party_module2/**
sonar.cpd.exclusions=**/tests/**/*

# Include test subdirectories in test scope
sonar.test.inclusions=**/tests/**/*